### ISSUE TITLE
Support for the largePoints feature in Vulkan

### ISSUE THREAD

**Issue by Irenapas** [bkaradzic/SwiftShader#1]
Please support the largePoints feature in Vulkan,
Test case: 
Compute N Bodies Simulation from Sascha Willems tests.
https://github.com/SaschaWillems/Vulkan/blob/master/examples/computenbody/computenbody.cpp

See also:
https://groups.google.com/forum/#!topic/swiftshader/LPZWJxIEoiQ

**Comment by bkaradzic** [comment]
This is just copy of https://swiftshader.googlesource.com/SwiftShader, you should open issue there...

**Comment by rossant** [comment]
For future reference, it seems this was fixed in March 2020 https://swiftshader-review.googlesource.com/c/SwiftShader/+/41948
